/* automatically generated by rust-bindgen 0.63.0 */
// silence lints since this is "autogenerated"
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unused)]

pub type undefined = ::core::ffi::c_uchar;
pub type byte = ::core::ffi::c_uchar;
pub type undefined2 = ::core::ffi::c_ushort;
pub type undefined4 = ::core::ffi::c_uint;
pub type ushort = ::core::ffi::c_ushort;
pub type wchar16 = ::core::ffi::c_ushort;
#[repr(u8)] // bindgen got this wrong
#[derive(Copy, Clone, Hash, PartialEq, Eq)]
pub enum DowsingSlotIndex {
    STORY_EVENT_DOWSING = 0,
    RUPEE_DOWSING = 1,
    QUEST_DOWSING = 2,
    CRYSTAL_DOWSING = 3,
    HEART_DOWSING = 4,
    CUBE_DOWSING = 5,
    LOOK = 6,
    TREASURE_DOWSING = 7,
    NO_DOWSING = 8,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Vec3f {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SaveFile {
    pub field_0x0: [undefined; 8usize],
    pub savedTimeHi: ::core::ffi::c_int,
    pub savedTimeLo: ::core::ffi::c_int,
    pub pos_t1: Vec3f,
    pub pos_t2: Vec3f,
    pub pos_t3: Vec3f,
    pub beaconPositions: [[Vec3f; 5usize]; 32usize],
    pub beedleShopPathSegment: ::core::ffi::c_int,
    pub beedleShopPathSegFrac: f32,
    pub field_0x7bc: [undefined; 4usize],
    pub pouch_items: [::core::ffi::c_int; 8usize],
    pub item_check_items: [::core::ffi::c_int; 60usize],
    pub file_area_index: ::core::ffi::c_int,
    pub file_hero_name: [wchar16; 8usize],
    pub storyFlags: [ushort; 128usize],
    pub item_flags: [ushort; 64usize],
    pub dungeon_flags: [[ushort; 22usize]; 8usize],
    pub field_0xbc4: [undefined; 3744usize],
    pub scene_flags: [ushort; 208usize],
    pub field_0x1c04: [undefined; 3680usize],
    pub tboxFlags: undefined,
    pub field_0x2a65: [undefined; 1279usize],
    pub enemyKillCounters: [ushort; 100usize],
    pub field8733_0x302c: [ushort; 100usize],
    pub temp_flags: [ushort; 4usize],
    pub zone_flags: [ushort; 252usize],
    pub field_0x32f4: [undefined; 8192usize],
    pub airPotionTimer: ::core::ffi::c_short,
    pub airPotionPlusTimer: ::core::ffi::c_short,
    pub staminaPotionTimer: ::core::ffi::c_short,
    pub staminaPotionPlusTimer: ::core::ffi::c_short,
    pub guardianPotionTimer: ::core::ffi::c_short,
    pub guardianPotionPlusTimer: ::core::ffi::c_short,
    pub field_0x5300: [undefined; 2usize],
    pub health_capacity: ::core::ffi::c_ushort,
    pub unusedHeartRelated: undefined2,
    pub current_health: ::core::ffi::c_ushort,
    pub load_room_t1: undefined2,
    pub field_0x530a: [undefined; 2usize],
    pub room_load_t3: ::core::ffi::c_short,
    pub angle_t1: ::core::ffi::c_short,
    pub angle_t2: ::core::ffi::c_short,
    pub angle_t3: ::core::ffi::c_short,
    pub beedleShopRotation: ::core::ffi::c_short,
    pub field_0x5316: [undefined; 2usize],
    pub sceneflag_index: ::core::ffi::c_short,
    pub field_0x531a: [undefined; 2usize],
    pub area_t1: [::core::ffi::c_char; 32usize],
    pub area_t2: [::core::ffi::c_char; 32usize],
    pub area_t3: [::core::ffi::c_char; 32usize],
    pub placedBeaconFlags: [byte; 32usize],
    pub skykeep_puzzle: [byte; 9usize],
    pub forced_layer_t1: byte,
    pub forced_layer_t2: byte,
    pub forced_layer_t3: byte,
    pub entrance_t1: byte,
    pub entrance_t1_load_flag: byte,
    pub entrance_t2: byte,
    pub entrance_t3: byte,
    pub field_0x53ac: [undefined; 1usize],
    pub new_file: byte,
    pub equipped_b_item: byte,
    pub field_0x53af: [undefined; 1usize],
    pub lastUsedPouchItemSlot: byte,
    pub shield_pouch_slot: byte,
    pub selectedDowsingSlot: DowsingSlotIndex,
    pub night_t1: byte,
    pub night_t3: byte,
    pub field_0x53b5: [undefined; 7usize],
    pub checksum: undefined4,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SavedSaveFiles {
    pub field_0x0: [undefined; 32usize],
    pub saveFiles: [SaveFile; 3usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FileManager {
    pub saveFiles: *mut SavedSaveFiles,
    pub saveTails: undefined4,
    pub FA: SaveFile,
    pub FB: SaveFile,
    pub skipFlags: [ushort; 16usize],
    pub skipflagChecksum: ::core::ffi::c_int,
    pub field6_0xa7ac: *mut wchar16,
    pub field_0xa7b0: [undefined; 50usize],
    pub heroname: [wchar16; 18usize],
    pub field_0xa806: [undefined; 54usize],
    pub field112_0xa83c: byte,
    pub isFileEmpty: [byte; 3usize],
    pub isFileUnk1: [byte; 3usize],
    pub isFileUnk2: [byte; 3usize],
    pub isFileUnk3: [byte; 3usize],
    pub field_0xa849: [undefined; 3usize],
    pub field120_0xa84c: byte,
    pub field_0xa84d: [undefined; 1usize],
    pub anticommit_flag: byte,
    pub field_0xa84f: [undefined; 1usize],
}
