
updateCurrentSword = 0x8005c110;
getGratitudeCrystalCount = 0x80252710;
FlagManager__getUncommittedFlags = 0x800bf5f0;
INPUT_BUFFER = 0x80599d0c;
AcItem__isBabyRattle = 0x80256c30;
Math__approachF = 0x802decd0;
FileManager__getDungeonFlags = 0x8000a460;
FlagManager__setFlagTo1 = 0x800bf5b0;
FileManager__getSceneflags = 0x8000a4e0;
SceneflagManager__setTempOrSceneflag = 0x800be2d0;
requestFileLoadFromDisk = 0x802f0060;
SPAWN_SLAVE = 0x805b3860;